//config module
export const UPDATE_TABLE_SIZE = 'UPDATE_TABLE_SIZE';
export const UPDATE_TABLE_DIMENSION = 'UPDATE_TABLE_DIMENSION';
export const UPDATE_TABLE_CELL_DIMENSION = 'UPDATE_TABLE_CELL_DIMENSION';

//game module
export const GAME_PREPEARE = 'GAME_PREPEARE';
export const GAME_CREATE_GAME_FIELD = 'GAME_CREATE_GAME_FIELD';
export const GAME_READY = 'GAME_READY';
export const GAME_START = 'GAME_START';
