//config module
export const UPDATE_TABLE_SIZE = 'UPDATE_TABLE_SIZE';
export const UPDATE_TABLE_DIMENSION = 'UPDATE_TABLE_DIMENSION';
export const UPDATE_TABLE_CELL_DIMENSION = 'UPDATE_TABLE_CELL_DIMENSION';

//game module
export const GAME_PREPEARE = 'GAME_PREPEARE';
export const GAME_CREATE_GAME_FIELD = 'GAME_CREATE_GAME_FIELD';
export const GAME_RECALCULATE_GAME_FIELD = 'GAME_RECALCULATE_GAME_FIELD';
export const GAME_RESIZE_GAME_FIELD = 'GAME_RESIZE_GAME_FIELD';
export const GAME_READY = 'GAME_READY';
export const GAME_START = 'GAME_START';
export const GAME_END = 'GAME_END';
export const GAME_GET_RIGHT_ANSWERS_VALUE = 'GAME_GET_RIGHT_ANSWERS_VALUE';
export const GAME_GET_NEXT_RIGHT_ANSWER = 'GAME_GET_NEXT_RIGHT_ANSWER';
export const GAME_USER_ANSWER = 'GAME_USER_ANSWER';